name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          version: latest
          install: true
          cache: true
          tool_versions: |
            "$(cat ./.tool_versions)"
      - run: bun ./my_app.js